version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: integration-test-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
